# Generated by Django 6.0.3 on 2026-03-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_num_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('view_reportes', 'Puede ver reportes de clientes')]},
        ),
    ]
