# Generated by Django 6.0.3 on 2026-03-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_cuenta_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
