# Generated by Django 6.0.3 on 2026-03-16 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cliente_num_cuenta_contacto_cuenta_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 9 dígitos y comenzar con 9 (ej: 912345678)', regex='^9\\d{8}$')]),
        ),
    ]
